name: Azure Deployment

on:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
            # Download and install the Azure CLI
            $url = "https://aka.ms/installazurecliwindows"
            $output = "$env:TEMP\AzureCLI.msi"
            Invoke-WebRequest -Uri $url -OutFile $output
            Start-Process msiexec.exe -Wait -ArgumentList "/I $output /quiet"

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      
